### ISSUE TITLE
FastGWR fails with singular matrices (is this intentional?)

### ISSUE THREAD

**Issue by alexandermichels** [Ziqi-Li/FastGWR#4]
I noticed that the code fails if there is a singular matrix because [you're using inverse](https://github.com/Ziqi-Li/FastGWR/blob/master/fastgwr/FastGWR.py#L186) rather than [pseudo-inverse](https://numpy.org/doc/stable/reference/generated/numpy.linalg.pinv.html). 

I wanted to check if this was intentional as I'm not an expert on GWR. If not, I'd be happy to make a pull request that catches the singular matrix error and then uses the pseudo-inverse.

Thanks!

**Comment by Ziqi-Li** [comment]
Fixed in #5
